cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path(r'^create/$', views.order_create, name='order_create'),
    path("payment/", views.order_payment, name="payment"),
    path("callback/", views.callback, name="callback"),
]

orders/models.py
from django.db import models
from myapp.models import products

from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _
from .constants import PaymentStatus
from django.contrib.auth.models import User


class Ordernow(models.Model):
    name = CharField(_("Customer Name"), max_length=254, blank=False, null=False)
    amount = models.FloatField(_("Amount"), null=False, blank=False)
    status = CharField( _("Payment Status"),
        default=PaymentStatus.PENDING,
        max_length=254,
        blank=False,
        null=False,
    )
    provider_order_id = models.CharField(
        _("Order ID"), max_length=40, null=False, blank=False
    )
    payment_id = models.CharField(
        _("Payment ID"), max_length=36, null=False, blank=False
    )
    signature_id = models.CharField(
        _("Signature ID"), max_length=128, null=False, blank=False
    )

    def __str__(self):
        return f"{self.id}-{self.name}-{self.status}"


class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    userid=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
   

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(products, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from django.contrib.auth.models import User


class OrderCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['userid']= forms.ModelChoiceField(label="user", widget=forms.HiddenInput(attrs={'value':user}), queryset=User.objects.all())
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city','userid']
    #def __init__(self, *args, **kwargs):
        #user = kwargs.pop('user')
        #super(OrderCreateForm, self).__init__(*args, **kwargs)
    
        
                  

orders/views.py
from django.shortcuts import render
from .models import *
from .forms import OrderCreateForm
from cart.cart import Cart
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import razorpay
import random
from django.http import HttpResponse


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
     

        form = OrderCreateForm(request.POST,initial={'userid': request.user.id}, user=request.user)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            #cart.clear()
        return render(request, 'orders/order/created.html', {'order': order})
    else:
        form = OrderCreateForm(initial={'userid': request.user.id}, user=request.user)
    return render(request, 'orders/order/create.html', {'form': form})


def order_payment(request):
    if request.method == "POST":
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        orderid=request.POST.get("provider_order_id")
        client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
        razorpay_order = client.order.create(
            {"amount": float(amount) * 100, "currency": "INR", "payment_capture": "1"}
        )
        order = Ordernow.objects.create(
            name=name, amount=amount, provider_order_id=razorpay_order['id']
        )
        order.save()
        o1=Order.objects.get(id=orderid)
        o1.paid=True
        o1.save()
        return render(
            request,
            "orders/order/payment.html",
            {
                "callback_url": "http://127.0.0.1:8000/orders/callback/",
                "razorpay_key": settings.RAZORPAY_KEY_ID,
                "order": order,
            },
        )
    return render(request, "orders/order/payment.html")


@csrf_exempt
def callback(request):
    cart = Cart(request)
    razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID,settings.RAZORPAY_KEY_SECRET))
    #    return client.utility.verify_payment_signature(response_data)

    if request.method == "POST":
        try:
            payment_id = request.POST.get("razorpay_payment_id", "")
            provider_order_id = request.POST.get("razorpay_order_id", "")
            signature_id = request.POST.get("razorpay_signature", "")
            params_dict={
                'razorpay_order_id':provider_order_id,
                'razorpay_payment_id':payment_id,
                'razorpay_signature':signature_id

            }
            print(params_dict)
            try:
                order = Ordernow.objects.get(provider_order_id=provider_order_id)
            except:
                return HttpResponse("505 not found inner")
            order.payment_id = payment_id
            order.signature_id = signature_id
            order.save()
            cart.clear()
            result=razorpay_client.utility.verify_payment_signature(params_dict)
            
            if result==True:
                amount=int(order.amount)
                
                try:
                   
                    '''res=razorpay_client.payment.capture(payment_id,{
                        "amount" : amount,
                        "currency" : "INR"
                        })
                    print(res)'''
                    order.status=PaymentStatus.SUCCESS
                    order.save()
                    return render(request, "orders/order/sucess.html")
                except:
                   
                    order.status=PaymentStatus.FAILURE
                    order.save()
                    return render(request, "orders/order/failure.html")
            else:
                
                order.status=PaymentStatus.FAILURE
                order.save()
                return render(request, "orders/order/failure.html")
        except:
            return HttpResponse("505 not found here")
        

orders/templates/orders/order/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Your Shopping Cart| Checkout
{% endblock %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>Order Create</h2>
            home/checkout
        </div>
    </div>
</div>
<!-- <div class="row p-5"id="ordercreate">
            <div class="col-md-6">
                <h1>Checkout</h1>
    
            {% csrf_token %}
            {{ form.as_p }}<br>
            <center><input type="submit" id="submitbtn"  class="btn btn-primary" value="Submit order"></center>
            </div>
            </div>-->
<div class="row p-5">
    <div class="col-md-6 p-5 text-center">
        <h2>Checkout</h2>
        <form method="post" id="loginform">
            {% csrf_token %}
            {{ form.as_p }}
            
            <br>
            <button class="btn btn-info btnlogin">Submit order</button>
        </form>
    </div>
    <div class="col-md-6 p-5">
        <h1> Your Order</h1>
        <ul class=list-group id="checkoutform">
            {% for item in cart %}
            <li class="list-group-item">
                <h6 class=" product-label mt-4">
                    <div class="border border-info p-2">{{ item.quantity }}*{{ item.product.name }}</div>
                    <br>
                    <span>Rs. {{ item.total_price }}</span>
            </li>
            {% endfor %}
            <div class="list-group-item active bg-info">Total Cost: Rs. {{ cart.get_total_price }}</div>
        </ul>

    </div>
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
<div class="row" id="bg10">
  <div class="col-md-12">
      <div class="text-center text-light p-4">
          home/order
          <h2>Order Placed</h2>
      </div>
  </div>
</div>
    <div class="container">
        <div class="row p-5">
          <div class="col-md-6">
            <img src="{% static 'payment.webp'%}" width="100%" height="90%" />
          </div>
     <div class="col-md-6 p-2" data-aos="flip-left">
      <div class="text-danger">               
        <h2 style="font-family: cursive;">Please click the button to proceed and do not refresh the page.</h2>
                <form action="{% url 'orders:payment' %}" method='POST'>
                  {% csrf_token %}
                  <input type="hidden" name="name" value="{{ order.email }}">
                  <input type="hidden" name="provider_order_id" value="{{ order.id }}">
                  <input type="hidden" name="amount" value="{{ cart.get_total_price }}">
                  <div>
                  <button type="submit" id="btnpay" class="btn btn-info">Redirect to Payment</button>
                  </div>
                </form>
              </div>
        </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/failure.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div col="col-md-12">
        failure!payment has not recieved yet.
    </div>
</div>

{% endblock %}

orders/templates/orders/order/payment.html
{% extends 'base.html' %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            home/pay
            <h2>Pay Now</h2>
        </div>
    </div>
  </div>
  <div class="container">
  <div class="row " id="pay">
<div class="col-md-12">
     <button type="submit" id="btnpay" class="btn btn-primary">Pay Now</button>
</div>
</div>
</div>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    
var options = {
    key: "{{razorpay_key}}",
    amount: "{{order.amount}}", 
    currency: "INR",
    name: "{{order.name}}",
    description: "Test Transaction",
    image: "https://www.pngfind.com/pngs/m/303-3031049_blello-mattress-mattress-hd-png-download.png",
    order_id: "{{order.provider_order_id}}",
    callback_url: "{{callback_url}}",
    redirect: true,
    prefill: {
        "name": "{{ order.name }}",
        "email": "{{ user.email }}",
        "contact": "9999999999"
    },
    notes: {
        "address": "Mattress"
    },
    theme: {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById("btnpay").onclick=function(e)
{
rzp1.open();
e.preventDefault();
}
</script>



{% endblock %}

orders/templates/orders/order/sucess.html
{% extends 'base.html' %}
{% block content %}
<div class="row P-5">
    <div col="col-md-12" data-aos="flip-left">
        <h1 class=" text-info mt-5 display-5 fw-bold" data-aos="fade-right">  Congratulations!You have successfully done the payment.</h1>
</div>
</div>
<div class="row pt-5 pb-5">
</div>
{% endblock %}