cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myapp/urls.py
from django.urls import path, include
from myapp import views
from django.contrib.auth.views import LoginView,LogoutView,PasswordResetView,    PasswordResetDoneView,   PasswordResetConfirmView,    PasswordResetCompleteView


urlpatterns = [
    path('home/',views.homeview.as_view()),
    path('about/',views.aboutview.as_view()),
    path('form/',views.formview.as_view()),
    path('mattress/',views.mattressview),
    path('contact/',views.contactview.as_view()),
    path('about/',views.aboutview.as_view()),
    path('services/',views.servicesview.as_view()),
    path('insertcontact/',views.insertcontact),
    path('blogs/',views.blogview),
    path('blogsdetail/<int:id>',views.blogsdetail),
    path('collection/',views.collection),
    path('Faq/',views.Faqview),
    path('product/<int:id>',views.productview),
    path('productdetail/<int:id>',views.productdetail),
    path('signup/',views.signupview),
    path('login/',LoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
    path('dolike/',views.dolike),
    path('shipping/',views.shippingview.as_view()),
    path('Signup/',views.signupview),
    path('insertemail/',views.insertemail),
    path('Myorder/',views.Myorderview),
    path('password-reset/', PasswordResetView.as_view(template_name='registration/password_reset.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('Addblogs/',views.Addblogsview.as_view()),
    path('insertblogs/',views.insertblogs),
  ]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
import datetime
from tinymce.models import HTMLField
from django.contrib.auth.forms import User

# Create your models here.

class contact(models.Model):
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=50)
    phone=models.CharField(max_length=10)
    message=models.TextField()
    class Meta:
        db_table="contact"

class category(models.Model):
    title=models.CharField(max_length=100)
    photo=models.ImageField(upload_to='category/')
    class Meta:
        db_table="category"
    def __str__(self):
        return self.title    

MYTAG=(
    ('best','best'),
    ('featured','featured'),
     ('latest','latest'), 
) 
AVAILABILITY=(
     ('pillows','pillows'),
    ('mattress','mattress'),
     ('curtains','curtains'), 
    ('cushions','cushions'),
    ('bed','bed'),
     ('bedsheets','bedsheets'),

)       

class products(models.Model):
    name=models.CharField(max_length=100)
    mrp=models.FloatField()
    price=models.FloatField()
    description=models.TextField()
    image=models.ImageField(upload_to='product/')
    photo2=models.ImageField(upload_to='product/',default="")
    categoryid=models.ForeignKey(category,on_delete=models.CASCADE,default="")
    rating=models.CharField(max_length=10,default="1")
    brandname=models.CharField(max_length=100,default="")
    material=models.CharField(max_length=100,default="")
    availability=models.CharField(max_length=50,choices=AVAILABILITY,default="")
    tag=models.CharField(max_length=50,choices=MYTAG,default="")
    class Meta:
        db_table="products"
    def __str__(self):
        return self.name 
    
class blogs(models.Model):
    STATUSS=(
        ('New','New'),
        ('Approved','Approved')
    )
    title=models.CharField(max_length=100)
    description=HTMLField()
    photo=models.ImageField(upload_to='blogs/')
    post_by=models.CharField(max_length=50,default="Admin")
    post_on=models.DateField(default=datetime.date.today())
    status=models.CharField(max_length=20,default='Approved',choices=STATUSS)
    userid=models.ForeignKey(User,on_delete=models.CASCADE, blank=True,null=True, default="1")
    class Meta:
        db_table="blogs"
    def __str__(self):
        return f"{self.title}----{self.status}"
    

class Faq(models.Model):
    Question=models.TextField()
    Answer=models.TextField()
    class Meta:
        db_table="Faq"
    def __str__(self):
        return self.Question    
    

class likenow(models.Model):
    productsid=models.ForeignKey(products,on_delete=models.CASCADE,default="")
    userid=models.ForeignKey(User,on_delete=models.CASCADE,default="")
    class Meta:
        db_table='likenow'

class subscribe(models.Model):
    email=models.CharField(max_length=50)
    class Meta:
        db_table="subscribe"
          
    
     

myapp/forms.py
from django import forms
from myapp.models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class contactform(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=contact

class signupform(UserCreationForm):
    class Meta:
        fields=('first_name','last_name','username','email','password1','password2')
        model=User

class subscribeform(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=subscribe

class Addblogsform(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=blogs       

myapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from myapp.forms import *
from myapp.models import *
from django.contrib.auth import login
from django.contrib import messages
from django.http import JsonResponse
import pdb
from django.db.models import Count
from django.shortcuts import render, redirect
from myapp.models import products
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from orders.models import *
from django.contrib import messages
# Create your views here.

def mattressview(request):
    coll=category.objects.all()[0:3]
    return render(request,"mattress.html",{'coll':coll})
class aboutview(TemplateView):
    template_name="about.html"
class formview(TemplateView):
    template_name="form.html"  
class homeview(TemplateView):
    template_name="home.html"
class contactview(TemplateView):
    template_name="contact.html"  
class aboutview(TemplateView):
    template_name="about.html"
class servicesview(TemplateView):
    template_name="services.html"
class shippingview(TemplateView):
    template_name="shipping.html"
class Addblogsview(TemplateView):
    template_name="Addblogs.html"

    
def insertcontact(request):
    if request.method=='POST':
        form=contactform(request.POST)   
        if form.is_valid():
            form.save()
            messages.success(request, "Message sent." )
            return redirect('/contact/')
    else:
            form=contactform()
            messages.error(request, "Error in sending message." )
    return render(request,"contact.html",{'form':form}) 
    
def blogview(request):
    blg=blogs.objects.filter(status='Approved').order_by('-id')
    return render(request,"blogs.html",{'blg':blg}) 

def blogsdetail(request,id):
    b=blogs.objects.get(id=id)
    return render(request,"blogsdetail.html",{'b':b}) 

def collection(request):
    c=category.objects.all()
    return render(request,"collection.html",{'c':c}) 

def Faqview(request):
    c=Faq.objects.all()
    return render(request,"Faq.html",{'c':c})

def productview(request,id):
    pro=products.objects.filter(categoryid_id=id).annotate(Count('likenow'))
    return render(request,"product.html",{'pro':pro}) 

def productdetail(request,id):
    c=products.objects.get(id=id)
    cart_product_form = CartAddProductForm()
    return render(request,"productdetail.html",{'c':c,'cart_product_form': cart_product_form}) 

def Myorderview(request):
    c=OrderItem.objects.select_related('order').filter(order__userid=request.user.id)
    return render(request,"Myorder.html",{'c':c})


def signupview(request):
    if request.method=='POST':
        form=signupform(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('/blogs/')
    else:
        form=signupform()
    return render(request,"registration/signup.html",{'form':form})

def dolike(request):
    #form=dolike()
    productid=request.GET['pid']
    userid=request.GET['uid']
    data={
        'is_taken': likenow.objects.filter(userid_id=userid,productid_id=productid).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'your like is already registered. you cannot do like again'
    else:
        form=likenow.objects.create(productid_id=productid,userid_id=userid)
        form.save()
        data['message']='your like is registred'
        return JsonResponse(data)
    return render(request,'product.html',{'form':form})

 
def insertemail(request):
    if request.method=='POST':
        form=subscribeform(request.POST)   
        if form.is_valid():
            form.save()
            return redirect('/mattress/')
    else:
            form=subscribeform()
    return render(request,"mattress.html",{'form':form}) 


def insertblogs(request):
    if request.method=='POST':
        form=Addblogsform(request.POST,request.FILES)   
        if form.is_valid():
            form.save()
            return redirect('/blogs/')
        else:
            form=Addblogsform()
    return render(request,"Addblogs.html",{'form':form}) 

myapp/templates/Addblogs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>Add blogs</h2>
            home/blogs
        </div>
    </div>
    <div class="row p-3 offset-3">
        <div class="col-md-6 ">
        <form action="/insertblogs/" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <input type="hidden" name="userid" value="{{user.id}}" />
         <input type="text" name="title" class="form-control" required placeholder="title" />
        </div>
    </div>
    <div class="row p-3 offset-3">
        <div class="col-md-6 ">
            <textarea required name="description" class="form-control" placeholder="description" ></textarea>
        </div>
        </div>
        <div class="row p-3 offset-3">
        <div class="col-md-6 ">
            <input type="file" name="photo" class="form-control" placeholder="photo" />
        </div>
    </div>
    <div class="row p-3 offset-3">
        <div class="col-md-6 ">
            <input type="text" name="post_by" class="form-control" placeholder="post_by" />
        </div>
    </div>
    <div class="row p-3 offset-3">
        <div class="col-md-6 ">
            <input type="date" name="post_on" class="form-control" placeholder="post_on" />
        </div>
    </div>
    <input type="hidden" name="status" value="New" />
    <div class="row p-3 offset-3">
        <div class="col-md-6 ">
            <button class=" btn border  my-3 btn-lg shadow-sm  w-100 bg-info">submit</button>
        </div> 
        </div>
    </div>
    
    </form>
        </div>
</div>
{% endblock %}

myapp/templates/Myorder.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>myorder</h2>
            home/order history
        </div>
    </div>
  </div>
<div class="row P-5">
    <table class="table">
        <tr>
            <th>Srno</th>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Order Date</th>
            <th>Payment Status</th>
        </tr>
    {% for c in c %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ c.product }}</td>
    <td>{{ c.price }}</td>
    <td>{{ c.quantity }}</td>
    <td>{{ c.order.updated }}</td>
    <td>{% if c.order.paid == True %} 
        PAID
        {% else %}
        NOT PAID
        {% endif %}
    </td>
  </tr>
    {% endfor %}
</table>
</div>

{% endblock %}

myapp/templates/base.html
{% load static %}

<html>

<head>
    <title>First page</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet" />
    <link href="{% static 'aos-master/dist/aos.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'style.js' %}" type="text/js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'aos-master/dist/aos.js' %}"></script>


    <script>
        $(document).ready(function () {
            AOS.init();
        });
    </script>

    <style>
        @media (max-width: 767px) {
            .carousel-inner .carousel-item>div {
                display: none;
            }

            .carousel-inner .carousel-item>div:first-child {
                display: block;
            }
        }

        .carousel-inner .carousel-item.active,
        .carousel-inner .carousel-item-next,
        .carousel-inner .carousel-item-prev {
            display: flex;
        }

        /* medium and up screens */
        @media (min-width: 768px) {

            .carousel-inner .carousel-item-end.active,
            .carousel-inner .carousel-item-next {
                transform: translateX(25%);
            }

            .carousel-inner .carousel-item-start.active,
            .carousel-inner .carousel-item-prev {
                transform: translateX(-25%);
            }
        }

        .carousel-inner .carousel-item-end,
        .carousel-inner .carousel-item-start {
            transform: translateX(0);
        }
    </style>

</head>

<body>
   
        
    
    <div class="container-fluid">

        <div class="row  p-3 " id="topheader">
            <div class="col-md-4">
                <img src="https://cdn.shopify.com/s/files/1/0454/2477/1240/files/logo_1_300x300.png?v=1623927662" alt=""
                    width="50%">
            </div>
            <div class="col-md-6 p-2">
                <nav class="navbar navbar-expand-lg ">
                    <div class="container-fluid">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="/mattress/">Home</a>
                                </li>
                        
                                <li class="nav-item ">
                                    <a class="nav-link" href="/contact/">
                                        Contact
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/about/">
                                        About
                                    </a>

                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/services/">
                                        Services
                                    </a>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/blogs/">
                                        Blogs
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/collection/">
                                        Shop
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/Faq/">
                                        Faq
                                    </a>
                                </li>
                                {% if user.is_authenticated %}
                                <li><a href="" class="nav-link">Hi, {{ user.username}}
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/Addblogs/">
                                        Addblogs
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/Myorder/">
                                        Myorder
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/logout/">
                                        Logout
                                    </a>
                                </li>

                                {% else %}
                                <li class="nav-item ">
                                    <a class="nav-link" href="/signup/">
                                        Register
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="/login/">
                                        login
                                    </a>
                                </li>
                               
                            {% endif %}

                        </div>
                    </div>
                </nav>
            </div>
            <div class="col-md-2 p-2">
               <a href="{% url 'cart:cart_detail' %}"> <button class="btn btn-info text-light float-right">Order Now <i
                        class="fa fa-bag-shopping px-1"></i></button></a>
                </nav>
            </div>
        </div>



        {% block content %}
        {% endblock %}
        <div class="row  p-4" id="bg98">
            <div class="col-md-3">
                <img src="{% static 'side.webp' %}" width="50%">
                <p>Softie Mattress Shop offers a wide range of luxurious and comfortable
                    mattresses for a restful night's sleep. Our expert staff are ready to assist you
                    in selecting the perfect mattress to suit your needs and budget..</p>
               <p>Visit us today for a better night's sleep</p>
                <i class="fa-brands fa-twitter border shadow-sm"></i>
                <i class="fa-brands fa-facebook border shadow-sm"></i>
                <i class="fa-brands fa-google border shadow-sm"></i>
                <i class="fab fa-tumblr border shadow-sm"></i>
            </div>
            <div class="col-md-3">
                <h5>SUBSCRIBE TO OUR NEWSLETTER</h5>
                <label>your e-mail address</label>
                <form action="/insertemail/" method="post">
                {% csrf_token %}
                <input type="email" class="form-control" name="email" placeholder=" Enter email" />
                <div>
                <a href="/mattress/"><button class=" btn border  my-3 btn-lg shadow-sm  bg-light">sign up</button></a>
                </form>
                </div>
            </div>
            <div class="col-md-3 namea">
                <h5>INFORMATION</h5>
                <a href="/Faq/"  class="text-decoration-none text-dark"><p>Help</p></a>
                    <a href="/about/"  class="text-decoration-none text-dark"><p>Information</p></a>
                    <a href="/contact/"  class="text-decoration-none text-dark"><p>privacy policy</p></a>
                    <a href="/shipping/" class="text-decoration-none text-dark"><p>shipping details</p></a>
                <img src="{% static 'girl.webp' %}" width="50%">
            </div>
            <div class="col-md-3">
                <h5>WE ARE @</h5>
                <i class="fa fa-house-chimney"></i>
                <span>address</span>
                <p>No:  58 A, green city,
                    bathinda</p>
                <hr />
                <i class="fa-solid fa-envelope"></i>
                <span>E-mail</span>
                <BR>
                <a href="">support@softie.com</a>
                <br />
                <a href="#">admin@softie.com</a>
                <hr />
                <i class="fa-solid fa-phone"></i>
                <span>Phone</span>
                <BR>
                0123 - 456 - 789
                <br />
                0000 - 1234 - 56789
                <hr />
                <i class="fa-solid fa-fax"></i>
                <span>Fax</span>
                <p>0000 - 1234 - 56789</p>
            </div>
        </div>
        <footer class="bg-light">
            <p class="my-5">© 2023 Softie Design Themes</p>

        </footer>
    </div>
    </div>
    <script>
 $(document).ready(function(){
 
 $(".btnlike").click(function(){
 var pid=$(this).parent().find('.pid').val();   
 var uid=$(this).parent().find('.uid').val();  
 //alert(pid);
 //alert(uid);
 $.ajax({
    dataType:'json',
    url:'/dolike/',
    data: {
        'pid':pid,
        'uid':uid
    },
    success:function(data)
    {
        //alert(data);
        if (data.is_taken) {
            alert(data.error_message);
        }
        else
        {
        alert(data.message);
        window.location.href='/contact/';    
        }
    },
    error:function(){
    //window.location.href='/mattress/';    
    //alert("error");
    }
 });
 });    
 });   
</script>
</body>

</html>

myapp/templates/blogs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>Blogs</h2>
            home/blogs
        </div>
    </div>
  </div>
  <div class="row">
    {% for b in blg %}
    <div id="box" class="col-md-6 p-3 blogs">
        <a href="/blogsdetail/{{ b.id }}">
        <h3>{{ b.title }}</h3>
        <img src="/media/{{ b.photo }}" width="100%" />
        <p>{{ b.post_by }} ({{ b.post_on }})</p>
    </a>
</div>
{% endfor %}
</div>
{% endblock %}

myapp/templates/blogsdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-12 text-center">
        <div class="bg-info text-center p-4">
        <h2>BLOGS DETAIL</h2>
    </div>
</div>

    <div class="col-md-8 offset-2 p-3 blogs">

        <h3>{{ b.title }}</h3>
        <img src="/media/{{ b.photo }}" width="100%" />
        <p>{{ b.description|safe }}....</p>
        <p>{{ b.postby }} ({{ b.poston }})</p>

    </div>

</div>
{% endblock %}

myapp/templates/collection.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>COLLECTION</h2>
            home/collection
        </div>
    </div>
  </div>
    <div class="row p-5" id="bgz">
        <div class="col-md-2 mt-3">
            <h5 class="text-center sidebar_title">Category</h5>
     </div>
    </div>
    <div class="row">
    {% for c in c %}
  
    <div id="box" class="col-md-4 p-3 category">
        <a href="/product/{{ c.id }}" class="text-decoration-none text-dark">
        <img src="/media/{{ c.photo }}" height="300px" width="100%" />
            <p class=" mt-2  fs-4 "> {{ c.title }}</p>
    </a>
        </div>
   

    {% endfor %}
</div>
{% endblock %}

myapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" id="bg10">
    <div class="col-md-12">
        <div class="text-center text-light p-4">
            <h2>Contact</h2>
            home/contact
        </div>
    </div>
  </div>
  {% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      <span aria-hidden="True">&times;</span>
    </button>
    {{ message }}
  </div>
</div>
{% endfor %}
<div class="row p-4">
    <div class="col-md-12">
        <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3447.1047050003313!2d74.95675982444922!3d30.
        23409050956244!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x391732ce585e8453%3A0x7cb4e61b05a49f68!2sG
        reen%20City%20Colony%2C%20Baba%20Farid%20Nagar%2C%20Bathinda%2C%20Pu
        njab%20151001!5e0!3m2!1sen!2sin!4v1681962981696!5m2!1sen!2sin" width="100%" height="450px"></iframe>
    </div>
</div>
<div class="row p-5  ">
    <div class="col-md-4 border-end">
        <div class="d-flex justify-content-center flex-column align-items-center">
        <i class="fa-solid fa-phone fs-1 text-success"></i>
        <br />
        <span>TALK TO US</span>
        <BR>
        Toll-Free: 0000 - 123 - 456789
        <br />
        Fax: 0000 - 123 - 456789
    </div>
    </div>
    <div class="col-md-4 border-end">
        <div class="d-flex justify-content-center flex-column align-items-center">
        <i class="fa-solid fa-envelope fs-1 text-warning"></i>
        <br />
        <span>CONTACT US</span>
        <BR>
        <a href="">mail@Softie.com</a>
        
        <a href=""> support@softie.com</a>
    </div>
    </div>
    <div class="col-md-4 ">
        <div class="d-flex justify-content-center flex-column align-items-center">
        <i class=" fa fa-location-arrow fs-1 text-primary"></i>
        <br />
        <span>LOCATION</span>
        <BR>
        <p>No: 58 A, green city,
            bathinda</p>
            </div>
    </div>
</div>
<div class="row p-3 offset-3">
    <div class="col-md-6 ">
    <form action="/insertcontact/" method="post">
        {% csrf_token %}
     <input type="text" name="name" class="form-control" required placeholder="Name" pattern="[A-Za-z ]*" />
    </div>
</div>
<div class="row p-3 offset-3">
    <div class="col-md-6 ">
        <input type="email" required name="email" class="form-control" placeholder="E-mail" />
    </div>
    </div>
    <div class="row p-3 offset-3">
    <div class="col-md-6 ">
        <input type="tel" name="phone" class="form-control" placeholder="Phone" maxlength="10" pattern="[6|7|8|9][0-9]{9}" />
    </div>
</div>
<div class="row p-3 offset-3">
    <div class="col-md-6 ">
       <textarea id="" cols="30" rows="10" name="message" required placeholder="Message" class="form-control"></textarea>
    </div>
</div>
<div class="row p-3 offset-3">
    <div class="col-md-6">
        <button class=" btn border  my-3 btn-lg shadow-sm  w-100 bg-info">send</button>
     </div>
    </form>
    </div>
    <div class="row pt-5 pb-5">
        <span class="border-bottom"></span>
    </div>
{% endblock %}

myapp/templates/form.html
{% load static %}
<html>
    <head>
        <title>form

        </title>
      
        <link rel="stylesheet" href="../../static/css/bootstrap-grid.css">
        <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
        <link href="boottemplate.css" type="text/css" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body id="maindiv">

     
    <div class="container-fluid">

        <div class="row"
        <div class="col-mid-6 offset p-5" id="myform">
    <h3>Register Form</h3>
<form>

    <label>Name</label>
    <input type="text "class="form-control"placeholder="Enter Name"required
    pattern="[A-Za-z ]*" />
    <label>Email</label>
    <input type="email"required class="form-control" placeholder="Enter Email" />

    <label>Password</label>

    <div class="input-group">
    <input type="password" class="form-control" placeholder="Enter Email" />

    <label>password</label>

    <div class="input-group">
    <input type="password" class="form-control" placeholder="Enter password" /> 
    <span class="input=group-text"><i class="fab fa-eye"></i></span>
    </div>


    <label>phone</label>
    <input type="tel" class="form-control" placeholder="Enter password" />
    "10" pattern="[6|7|8|9][0-9]{9}" />

    <label>Address</label>
    <textarea class="form-control" placeholder="Enter Address"></textarea>

    <br/>
    <label>Course</label>
    <select class="form-control">
    <option value="">-select course-</option> 
    <option>Python</option>
    <option>PHP</option> 
    <option>HTML</option>
    <option>CSS</option> 
    </select>

    <label>pic</label>
    <input type="file" class="form-control" accept=".png,.jpg" />

    <label>date</label>
    <input type="date" class="form-control"

    <label>time</label>
    <input type="time" class="form-control"

    <br/>
    <input type="checkbox" /><label> I accept the terms</label>

    <br/>
    <input type="submit" class="btn btn-sucess" value="Register" />
    <input type="reset" class="btn btn-danger" value="cancel" />

    
</form>
</div>
</div>
</body>
</html>